### ISSUE TITLE
Broken site causes PHP errors when Studio starts

### ISSUE THREAD

**Issue by jeroenpf** [Automattic/studio#468]
### Quick summary

I have tested with a site where the `feedburner-form` plugin was installed. The plugin only works on PHP versions lower than 8 as it uses the 'create_function` function which has been removed in PHP >8.

I configured the site to run on PHP 7.4 and I can use the site just fine. However, when starting Studio, I still see errors related to `create_function` in the output.

Here is an example:

```
PHPExecutionFailureError2: PHP.run() failed with exit code 255 and the following output: PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /var/www/html/wp-content/plugins/feedburner-form/control/widgets.php:214
Stack trace:
#0 /var/www/html/wp-content/plugins/feedburner-form/feedburner-form.php(45): require()
#1 /var/www/html/wp-settings.php(522): include_once('/var/www/html/w...')
#2 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1375): require('/var/www/html/w...')
#3 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1294): WP_CLI\Runner->load_wordpress()
#4 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#5 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#6 phar:///tmp/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#7 phar:///tmp/wp-cli.phar/php/boot-phar.php(20): include('phar:///tmp/wp-...')
#8 /tmp/wp-cli.phar(4): include('phar:///tmp/wp-...')
#9 /tmp/run-cli.php(37): require('/tmp/wp-cli.pha...')
#10 {main}
  thrown in /var/www/html/wp-content/plugins/feedburner-form/control/widgets.php on line 214

```

### Steps to reproduce

1. Start Studio with `npm start`
2. Have a PHP 7.4 site with a broken plugin like the feedburner-form or add custom code that tries to use the `create_function` function.
3. Observe that the site works fine.
4. Now start Studio again and you should see the errors pop up in the terminal.

### What you expected to happen

There should not be any errors while Studio is starting.

### What actually happened

I got a bunch of errors in the terminal indicating that something is broken.

### Impact

One

### Available workarounds?

No but the app is still usable

**Comment by katinthehatsite** [comment]
@jeroenpf is that the plugin you are referring to: https://wordpress.org/plugins/feedburner-form/ ?

**Comment by katinthehatsite** [comment]
Here is what I tested: 
 
I created a simple plugin that uses `create_function`:

```
<?php
/**
 * Plugin Name: Deprecated Function Plugin
 * Plugin URI:  https://example.com/
 * Description: A plugin to demonstrate the use of a deprecated PHP function.
 * Version:     1.0
 * Author:      Your Name
 * Author URI:  https://example.com/
 */

// Using the deprecated create_function
function dfp_add_action() {
    $callback = create_function('$a', 'return "Deprecated function executed: " . $a;');
    return $callback('Sample Text');
}

// Output the result in the footer to avoid header issues
function dfp_output_in_footer() {
    echo dfp_add_action();
}

// Hook into WordPress' 'wp_footer' action
add_action('wp_footer', 'dfp_output_in_footer');
```

* I started the site with PHP 7.4 and it worked as expected
* I started the site with PHP 8.0 and got the following error:

```
'PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /var/www/html/wp-content/plugins/deprecated-function-plugin/deprecated-function-plugin.php:13\n' +
      'Stack trace:\n' +
      '#0 /var/www/html/wp-content/plugins/deprecated-function-plugin/deprecated-function-plugin.php(19): dfp_add_action()\n' +
      "#1 /var/www/html/wp-includes/class-wp-hook.php(324): dfp_output_in_footer('')\n" +
      '#2 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n' +
      '#3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n' +
      "#4 /var/www/html/wp-includes/general-template.php(3081): do_action('wp_footer')\n" +
      '#5 /var/www/html/wp-includes/template-canvas.php(25): wp_footer()\n' +
      "#6 /var/www/html/wp-includes/template-loader.php(106): include('/var/www/html/w...')\n" +
      "#7 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...')\n" +
      "#8 /var/www/html/index.php(17): require('/var/www/html/w...')\n" +
      '#9 {main}\n' +
      '  thrown in /var/www/html/wp-content/plugins/deprecated-function-plugin/deprecated-function-plugin.php on line 13\n'
```

The app did not crash and I got the error in the console when trying to start the site. I am not sure what is a viable solution here, to be honest. From my understanding, this is usually responsibility of plugin and theme developers to ensure their product is compatible with different PHP versions. Speaking with @kozer , we discussed that we might not need to solve for this case. Alternatively, we could add some sort of banner or UI when the user is using a plugin or a theme that uses a deprecated function that is causing compatibility issues. 

What are your thoughts @jeroenpf and @kozer ?

**Comment by kozer** [comment]
As we discussed, this issue is not handled in other parts of the system like WPCOM, playground etc. It's user's responsibility to make it work, as he knows the risks by using outdated plugins, and switching PHP and WordPress versions. 
The logs are fine for me, as they don't crash the app, neither create any issues, and are useful for us, to know if there is any underlying issues

**Comment by jeroenpf** [comment]
The problem that I encountered is that even if i configure my site to run with PHP 7.4, i get errors in the console when i start studio (not start the site). 

The reason i reported this as an issue is that apparently something is running (perhaps CLI, perhaps something else?) that uses a PHP version different from the one configured for the site. I think we should at least understand why it happens and then decide if it needs to be fixed.

**Comment by katinthehatsite** [comment]
> The problem that I encountered is that even if i configure my site to run with PHP 7.4, i get errors in the console when i start studio (not start the site).

Hmm, I am not seeing any errors when starting Studio after configuring 7.4. Do you have a copy of the `feedburner-form` plugin I can test with? I tried to download it but it is not available anymore in the dotOrg repo

**Comment by katinthehatsite** [comment]
Related PR that was deployed: https://github.com/Automattic/studio/pull/505

**Comment by katinthehatsite** [comment]
I am still seeing the error after the fix has been deployed for the sample site that we used for testing:

```
TypeError: Cannot set property message of #<ErrorEvent2> which has only a getter
    at w (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:129305:149)
    at b.logMessage (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:129363:7)
    at b.error (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:129440:10)
    at UnhandledRejectionsTarget.e (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:127701:7220)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at UnhandledRejectionsTarget.dispatchEvent (node:internal/event_target:742:26)
    at t.wasmExports.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:127652:11809)
    at invoke_iiiii (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:97499:14)
    at php.wasm.php_execute_script (wasm://wasm/php.wasm-039ec376:wasm-function[11228]:0x66479c)
    at php.wasm (wasm://wasm/php.wasm-039ec376:wasm-function[15988]:0x80f2c3)
    at php.wasm.dynCall_ii (wasm://wasm/php.wasm-039ec376:wasm-function[13144]:0x752ed3)
    at ret.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:96884:22)
    at t.wasmExports.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:127652:11591)
    at invoke_ii (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:97466:14)
    at php.wasm.wasm_sapi_handle_request (wasm://wasm/php.wasm-039ec376:wasm-function[9680]:0x5d996f)
    at ret.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:96884:22)
```

**Comment by jeroenpf** [comment]
I am getting the same error and i am not sure why. There is a slight chance it is related to the original issue that i reported but I don't immediately see a causation.

The error reported in this issue seems to be related to: https://github.com/Automattic/studio/blob/trunk/vendor/wp-now/src/execute-wp-cli.ts#L20

This code is used to execute CLI commands and it does not seem to use the PHP version of the site, which is why we see the `PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /var/www/html/wp-content/plugins/feedburner-form/control/widgets.php:214` error in the console. This could potentially interfere with some commands that are necessary to make the site function properly.

**Comment by katinthehatsite** [comment]
It seems that we are running into two issues here as determined in Slack huddles:

* the first issue is the following error:

```
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^

TypeError: Cannot set property message of #<ErrorEvent2> which has only a getter
    at w (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:129305:149)
    at b.logMessage (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:129363:7)
    at b.error (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:129440:10)
    at UnhandledRejectionsTarget.e (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:127701:7220)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at UnhandledRejectionsTarget.dispatchEvent (node:internal/event_target:742:26)
    at t.wasmExports.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:127652:11809)
    at invoke_iiiii (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:97499:14)
    at php.wasm.php_execute_script (wasm://wasm/php.wasm-039ec376:wasm-function[11228]:0x66479c)
    at php.wasm (wasm://wasm/php.wasm-039ec376:wasm-function[15988]:0x80f2c3)
    at php.wasm.dynCall_ii (wasm://wasm/php.wasm-039ec376:wasm-function[13144]:0x752ed3)
    at ret.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:96884:22)
    at t.wasmExports.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:127652:11591)
    at invoke_ii (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:97466:14)
    at php.wasm.wasm_sapi_handle_request (wasm://wasm/php.wasm-039ec376:wasm-function[9680]:0x5d996f)
    at ret.<computed> (/Users/katerynakodonenko/Documents/A8C-Projects/studio/studio/.webpack/main/siteServerProcess.js:96884:22)
```

* the second issue is that we are passing a default PHP version when running plugins rather than the PHP version that the site is using and that's why the `feedburner-form` throws an error with PHP `7.4` even tough it should not as the `create_function` exists there.

**Comment by fluiddot** [comment]
> * the second issue is that we are passing a default PHP version when running plugins rather than the PHP version that the site is using and that's why the `feedburner-form` throws an error with PHP `7.4` even tough it should not as the `create_function` exists there.

This issue has been solved in https://github.com/Automattic/studio/pull/517.
