### ISSUE TITLE
Unable to resolve symlinked path in plugin on macOS

### ISSUE THREAD

**Issue by tbradsha** [Automattic/studio#728]
### Quick summary

When creating a symlinking to the Jetpack plugin in wp-content/plugins, I get a PHP fatal.

### Steps to reproduce

1. Clone the Jetpack repo somewhere: https://github.com/Automattic/jetpack
2. Build the plugin: `jetpack build plugins/jetpack`
3. Create a symlink to the Jetpack plugin folder (e.g. `ln -s /path/to/studio/site/wp-content/plugins /path/to/jetpack/repo/projects/plugins/jetpack`
4. Visit the site and activate the plugin.

### What you expected to happen

The Jetpack plugin should run.

### What actually happened

One gets fatal. Oddly it does resolve this path:

`Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/vendor/jetpack-autoloader/class-autoloader-handler.php`

But not this one, which most certainly does exist:

`/Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/jetpack_vendor/automattic/jetpack-assets/actions.php`

```
Fatal error: Uncaught Error: Failed opening required '/Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/jetpack_vendor/automattic/jetpack-assets/actions.php' (include_path='.:') in /Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/vendor/jetpack-autoloader/class-version-loader.php:109
Stack trace:
#0 /Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/vendor/jetpack-autoloader/class-autoloader-handler.php(124): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ14_1\al5_0_0\Version_Loader->load_filemap()
#1 /Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/vendor/jetpack-autoloader/class-autoloader.php(80): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ14_1\al5_0_0\Autoloader_Handler->activate_autoloader(Array)
#2 /Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/vendor/autoload_packages.php(13): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ14_1\al5_0_0\Autoloader::init()
#3 /Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/jetpack.php(144): require_once('/Users/jetpack/GitH...')
#4 /var/www/html/wp-settings.php(526): include_once('/Users/jetpack/GitH...')
#5 /var/www/html/wp-config.php(102): require_once('/var/www/html/w...')
#6 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#7 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...')
#8 /var/www/html/wp-admin/index.php(10): require_once('/var/www/html/w...')
#9 {main} thrown in /Users/jetpack/GitHub/jetpack/projects/plugins/jetpack/vendor/jetpack-autoloader/class-version-loader.php on line 109
```

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Mac Silicon

**Comment by Robertght** [comment]
I believe this may be related: https://github.com/Automattic/studio/issues/20

I'm pinging @wojtekn for an extra look.

**Comment by tbradsha** [comment]
Indeed, I had asked if I should comment in that issue or make a new one, but never got a reply. I'll note that supposedly symlinks were fixed for macOS (#510), but the comments in that other issue after that fix are hit-or-miss.

**Comment by bgrgicak** [comment]
I tested this now and was able to symlink multiple plugins and themes including Jetpack.
@tbradsha could you please try again with the latest version of Studio?

**Comment by bgrgicak** [comment]
We recently fixed a related issue with symlinks https://github.com/Automattic/studio/pull/809

**Comment by wojtekn** [comment]
@bgrgicak I reviewed this today and reproduced the issue.

Based on my current understanding of Symlink Manager, I think it can't work as it is implemented now.

The file exists on my file system:

```
/Users/USERNAME/Sites/jetpack/projects/plugins/jetpack/jetpack_vendor/automattic/jetpack-assets/actions.php
```

I have a symlink in my Studio site's `wp-content/plugins`:

```
jetpack -> /Users/USERNAME/Sites/jetpack/projects/plugins/jetpack
```

The path `jetpack/jetpack_vendor/automattic/jetpack-assets/actions.php` resolves when I access it from my plugins directory in Mac filesystem context.

Symlink manager mounts `/var/www/html/wp-content/plugins/jetpack` that points to `/Users/USERNAME/Sites/jetpack/projects/plugins/jetpack`.

Then, PHP running in Studio tries to load `/Users/USERNAME/Sites/jetpack/projects/plugins/jetpack/jetpack_vendor/automattic/jetpack-assets/actions.php` as this path is hardcoded in Composer's autoload class list generated during Jetpack plugin build.

CC @fredrikekelund

**Comment by fredrikekelund** [comment]
In the case you shared, @wojtekn, `SymlinkManager` doesn't touch `/var/www/html/wp-content/plugins/jetpack` – it only mounts a folder at `/Users/USERNAME/Sites/jetpack/projects/plugins/jetpack`. It is not immediately clear to me why this wouldn't work, but I can take a closer look.

**Comment by tbradsha** [comment]
@bgrgicak the above answers have more technical info than I can provide, but I can confirm it's also not working for me in v1.3.7.

**Comment by bgrgicak** [comment]
Implemented in https://github.com/Automattic/studio/pull/1425

**Comment by tbradsha** [comment]
I can confirm this is working fine on macOS using 1.5.3-beta2!
